apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: mlflow
spec:
  storageClassName: local-path

  volumeName: postgres-pv

  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 5Gi